[project]
name = "poc-mini-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastembed>=0.7.4",
    "numpy>=2.4.2",
    "psutil>=7.2.2",
    "sqlite-vec>=0.1.6",
]
